<a href="https://colab.research.google.com/github/nidhin-koshy/Notebooks/blob/master/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics

In this module we will review some basic operations in python which are essential for getting started with Python.

Python is one of the popular platforms for ML and Data Analytics prototyping. 

## Advantages
* Ease of coding - very high level syntax
* Numerical libraries for mathematical computations - [SciPy](https://www.scipy.org/), [NumPy](http://www.numpy.org/),
* Extensive ML libraries - [Scikit Learn](https://scikit-learn.org/stable/), [Tensorflow](https://www.tensorflow.org/), [PyTorch](https://pytorch.org/)

## Basic math operations

In [0]:
# Basic Math Operations
var1 = 4
var2 = 3
var_add = var1 + var2
var_mult = var1 * var2
var_div = var1/var2
var_floor = var1//var2
var_exp = var1**var2

print("var1 = ", var1, "var2 = ", var2,"var_add = ", var_add,"var_mult = ", var_mult,"var_div = ", var_div, "var_floor = ", var_floor,'var_exp = ',var_exp)
print("type(var1) = ", type(var1), "type(var2) = ", type(var2),"type(var_div) = ", type(var_div),"type(var_floor) = ", type(var_floor), "type(var_exp) = ", type(var_exp))

var1 =  4 var2 =  3 var_add =  7 var_mult =  12 var_div =  1.3333333333333333 var_floor =  1 var_exp =  64
type(var1) =  <class 'int'> type(var2) =  <class 'int'> type(var_div) =  <class 'float'> type(var_floor) =  <class 'int'> type(var_exp) =  <class 'int'>


## Lists, Tuples and Dictionaries

Lists, tuples and dictionaries are data types that can be used to represent a collection of data.

### Lists
Lists are similar to numerical arrays, but are more flexible and each element can hold any data type. Further, the contents of a list can be edited. The size of the list can be increased, decreased, and an element in the list can be edited.

In [42]:
#Lists
var_list = [1,2,3,4] #list of numericals
print("var_list = ", var_list)
var_list_mixed=[1,'India',[2,3],4.0] #mixed list, with numericals, strings,list
print("var_list_mixed = ",var_list_mixed)
var_list_mixed.append("new element") #add an element to a list
print("var_list_mixed = ",var_list_mixed)
var_list_mixed[0] = "Zero Index" #edit an element of the list
print("var_list_mixed = ",var_list_mixed)
var_list_mixed.pop(1) #remove an element in a list. Similar function is del var_list_mixed[2]
print("var_list_mixed = ",var_list_mixed)
#Indexing
print("First two elements of var_list_mixed = ", var_list_mixed[0:2]) #var[start:stop+1]
print("Last two elements of var_list_mixed = ", var_list_mixed[-2:]) #var[-start:]

var_list =  [1, 2, 3, 4]
var_list_mixed =  [1, 'India', [2, 3], 4.0]
var_list_mixed =  [1, 'India', [2, 3], 4.0, 'new element']
var_list_mixed =  ['Zero Index', 'India', [2, 3], 4.0, 'new element']
var_list_mixed =  ['Zero Index', [2, 3], 4.0, 'new element']
First two elements of var_list_mixed =  ['Zero Index', [2, 3]]
Last two elements of var_list_mixed =  [4.0, 'new element']


### Exercise
* How can we extract data from non-contiguous indexes in a list?

### Tuples

 Tuples are simlar to lists, but its elements are not editable.

In [51]:
# Tuples. Tuples are similar to lists but cannot be edited.
var_tuple = (1,2,3,4)
print("var_tuple = ",var_tuple)
var_tuple_mixed=(1,'India',[2,3],4)
print("var_tuple_mixed = ",var_tuple_mixed)
print("var_tuple_mixed[1] = ",var_tuple_mixed[1])
#var_tuple_mixed[0] = 2 # This will trigger an error message

var_tuple =  (1, 2, 3, 4)
var_tuple_mixed =  (1, 'India', [2, 3], 4)
var_tuple_mixed[1] =  India


### Exercise
* Can we edit a list which is an element of an array?

### Dictionaries
Similar to lists and tuples, dictionary is also a collection of elements. Each element of a dictionary consists of a "key" and "value" pair. The elements of a dictionary are indexed by the "key" value. 

In [66]:
#Dictionaries
var_dict={"India":"Delhi",'UK':'London',"USA":"Washington D.C."} #Dictionaries are initialized using curly brackets
print("var_dict = ", var_dict)
print("var_dict['UK'] = ", var_dict["UK"]) # elements are indexed using key values
var_dict["new"] = [1,2,3,4] # add a new element
print("var_dict = ", var_dict)
var_dict['UK'] = "Manchester"
print("var_dict = ", var_dict)
del var_dict['UK']
print("var_dict = ", var_dict)

var_dict =  {'India': 'Delhi', 'UK': 'London', 'USA': 'Washington D.C.'}
var_dict['UK'] =  London
var_dict =  {'India': 'Delhi', 'UK': 'London', 'USA': 'Washington D.C.', 'new': [1, 2, 3, 4]}
var_dict =  {'India': 'Delhi', 'UK': 'Manchester', 'USA': 'Washington D.C.', 'new': [1, 2, 3, 4]}
var_dict =  {'India': 'Delhi', 'USA': 'Washington D.C.', 'new': [1, 2, 3, 4]}


## Assignment in Python

Internally in Python, a variable is a pointer to a target, with the target holding the data. Hence, when we assign (=) a value to a variable, the variable's pointer is edited to point to the new target. 

In the case of numericals and strings, the use of (=) does not have any ambiguties, and the results are as one would expect, as shown in the first set of statements below.

However, when using mutable objects like lists or classes, the assignment(=) changes the variable's pointer to point to the same target. And any changes to the target is reflected in all objects pointing to that target.

Reference - https://realpython.com/python-variables/

In [72]:
#assignment operator gives expected output for numericals and strings
a=5
b=10
c=20
print("(a,b,c) = ", (a,b,c))
a=c
b=c
c=10
print("(a,b,c) = ", (a,b,c))
print("id(a,b,c) = ", (id(a),id(b),id(c))) # id returns the id of the target

a="India"
b="UK"
c="US"
print("(a,b,c) = ", (a,b,c))
a=c
b=c
c="Canada"
print("(a,b,c) = ", (a,b,c))
print("id(a,b,c) = ", (id(a),id(b),id(c))) # id returns the id of the target

(a,b,c) =  (5, 10, 20)
(a,b,c) =  (20, 20, 10)
id(a,b,c) =  (10969408, 10969408, 10969088)
(a,b,c) =  ('India', 'UK', 'US')
(a,b,c) =  ('US', 'US', 'Canada')
id(a,b,c) =  (140374787268368, 140374787268368, 140374787264784)


In [73]:
# For lists, any change to the target affects all variables pointing to that target
a=[5,10]
b=[10,20]
c=[20,30]
print("(a,b,c) = ", (a,b,c))
print("id(a,b,c) = ", (id(a),id(b),id(c))) # id returns the id of the target
a=c #use the copy method for lists or use the copy.deepcopy functions
b=c
c[1]= 1
print("(a,b,c) = ", (a,b,c))
print("id(a,b,c) = ", (id(a),id(b),id(c))) # id returns the id of the target

(a,b,c) =  ([5, 10], [10, 20], [20, 30])
id(a,b,c) =  (140374796542152, 140374787384136, 140374787383368)
(a,b,c) =  ([20, 1], [20, 1], [20, 1])
id(a,b,c) =  (140374787383368, 140374787383368, 140374787383368)


## Logical operators and conditional statements

Logical operators in Python are (==, !=, > , <, >=, <=) . Nesting of logical operators is achived using keywords "and" and "or"

In [80]:
a = 1
b = 1
c = 2
if(a>b):  
  if a>c:
    print("Max = ", a) # Note that there is no curly brackets to indicate a code section. Code section is indicated using indentation.
  else:
    print("Max = ", c)
elif (c<b):
  print("Max = ", b)
else:
  print("Max = ", c)


Max =  2


In [88]:
a = 5
b = 4
c = 2
if a>=b and a>=c:
  print("Max = ", a)
elif (b>=a and b>=c):
  print("Max = ", b)
else:
  print("Max = ", c)

Max =  5


## Loops

In [0]:
#Loops
import numpy as np # import numpy library to be able to call numpy.arange() function

print("\nfor loop - loop over numbers: ")
for count in range(0,10,1): #range(start,stop,step)
  print(count,end=' ')

print("\nfor loop - loop over a list")
colors = ["red", "blue", "green", "black"]
for color in colors:
  print(color, "", end='')

print("\nfor loop - loop over floating point numbers")
for t in np.arange(0.0,1.0,0.10): # arange(start, stop, step) . for floating point iterates. similar function numpy.linspace
 print(t, end=' ')

print("\nwhile loop")
count = 10
while count>0:
  print(count, end=" ")
  count-=1


for loop - loop over numbers: 
0 1 2 3 4 5 6 7 8 9 
for loop - loop over a list
red blue green black 
for loop - loop over floating point numbers
0.0 0.1 0.2 0.30000000000000004 0.4 0.5 0.6000000000000001 0.7000000000000001 0.8 0.9 
while loop
10 9 8 7 6 5 4 3 2 1 

## Functions

In [0]:
def division(dividend,divisor):
  quotient = dividend/divisor
  return quotient

print(division(4,3)) #implicit argument mapping
print(division(dividend=4,divisor=3)) # explicit argument mapping 
print(division(divisor=4,dividend=3))

def my_arange(start,stop,step=1):
  my_list =[]
  current_val = start
  while (current_val < stop):
    my_list.append(current_val)
    current_val+=step
  return my_list

print("Function call with implicit argument mapping - my_arange(-10,10,1.5) = ", my_arange(-10,10,1.5))
print("Function call using default values - my_arange(-10,10) = ",my_arange(-10,10))
print("Function call with explicit argument mapping - my_arange(step=0.1,stop=1,start=0) = ", my_arange(step=0.1,stop=1,start=0))

1.3333333333333333
1.3333333333333333
0.75
Function call with implicit argument mapping - my_arange(-10,10,1.5) =  [-10, -8.5, -7.0, -5.5, -4.0, -2.5, -1.0, 0.5, 2.0, 3.5, 5.0, 6.5, 8.0, 9.5]
Function call using default values - my_arange(-10,10) =  [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Function call with explicit argument mapping - my_arange(step=0.1,stop=1,start=0) =  [0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7, 0.7999999999999999, 0.8999999999999999, 0.9999999999999999]


## Vectors and Matrices

Numpy allows us to define vectors and matrices and provides built-in functions to compute matrix operations.


In [91]:
#Vectors and vector multiplication
import numpy as np

var_array = np.array([1,2,3,4])
print("Shape of var_array = ", var_array.shape)

var_row_vector = np.array([[1,2,3,4]])
print("Shape of var_row_vector = ", var_row_vector.shape)


print("var_array = ", var_array, ". var_vector = ", var_row_vector )

print("Transpose of var_array = ", var_array.T)
print("Transpose of var_row_vector = \n", var_row_vector.T)

print("Array multiplication with scalar = ", var_array * 3)
print("Vector multiplication with scalar = ", var_row_vector * 3)

var2_array = np.array([5,4,3,2])
var2_row_vector = np.array([[5,4,3,2]])

print("var_array * var2_array = ", var_array * var2_array.T) # '*' operator does an element wise multiplications
print("Example of Broadcasting (a terminology used in Python). var_row_vector * var2_row_vector.T = \n", var_row_vector * var2_row_vector.T) # example of broadcasting, where the arrays are expanded to match the dimensions 



Shape of var_array =  (4,)
Shape of var_row_vector =  (1, 4)
var_array =  [1 2 3 4] . var_vector =  [[1 2 3 4]]
Transpose of var_array =  [1 2 3 4]
Transpose of var_row_vector = 
 [[1]
 [2]
 [3]
 [4]]
Array multiplication with scalar =  [ 3  6  9 12]
Vector multiplication with scalar =  [[ 3  6  9 12]]
var_array * var2_array =  [5 8 9 8]
Example of Broadcasting (a terminology used in Python). var_row_vector * var2_row_vector.T = 
 [[ 5 10 15 20]
 [ 4  8 12 16]
 [ 3  6  9 12]
 [ 2  4  6  8]]


In [92]:
# Matrix multiplication

print("matrix mult of var_row_vector and var2_row_vector = \n", np.matmul(var_row_vector.T,var2_row_vector))

M1 = np.random.randint(1,5,(8,2))
M2 = np.random.randint(1,5,(8,2))

print("matrix M1 = \n", M1, "\n matrix M2 = \n", M2)
print("M1.*M2 = \n", np.multiply(M1,M2))
print("M1*M2.T = \n", np.matmul(M1,M2.T))

matrix mult of var_row_vector and var2_row_vector = 
 [[ 5  4  3  2]
 [10  8  6  4]
 [15 12  9  6]
 [20 16 12  8]]
matrix M1 = 
 [[3 2]
 [3 3]
 [3 3]
 [3 4]
 [4 3]
 [1 4]
 [1 2]
 [2 4]] 
 matrix M2 = 
 [[4 2]
 [2 1]
 [4 4]
 [1 2]
 [2 4]
 [2 4]
 [1 2]
 [2 2]]
M1.*M2 = 
 [[12  4]
 [ 6  3]
 [12 12]
 [ 3  8]
 [ 8 12]
 [ 2 16]
 [ 1  4]
 [ 4  8]]
M1*M2.T = 
 [[16  8 20  7 14 14  7 10]
 [18  9 24  9 18 18  9 12]
 [18  9 24  9 18 18  9 12]
 [20 10 28 11 22 22 11 14]
 [22 11 28 10 20 20 10 14]
 [12  6 20  9 18 18  9 10]
 [ 8  4 12  5 10 10  5  6]
 [16  8 24 10 20 20 10 12]]


# Debugging in Python Notebooks
Once you encounter an error, you can initiate a debug prompt by running "%debug" in a code cell (as shown in the cell below).

For more details refer: https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.06-Errors-and-Debugging.ipynb

In [0]:
%debug

## Resources

Official Python tutorial - https://docs.python.org/3/tutorial/