<a href="https://colab.research.google.com/github/nidhin-koshy/Notebooks/blob/master/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics for ML and Data Analytics

Python is one of the popular platforms for ML and Data Analytics prototyping. 

## Advantages
* Ease of coding - very high level syntax
* Numerical libraries for mathematical computations - [SciPy](https://www.scipy.org/), [NumPy](http://www.numpy.org/),
* Extensive ML libraries - [Scikit Learn](https://scikit-learn.org/stable/), [Tensorflow](https://www.tensorflow.org/), [PyTorch](https://pytorch.org/)

## Basic math operations

In [7]:
# Basic Math Operations
var1 = 4
var2 = 3
var_add = var1 + var2
var_mult = var1 * var2
var_div = var1/var2
var_floor = var1//var2
var_exp = var1**var2

print("var1 = ", var1, "var2 = ", var2,"var_add = ", var_add,"var_mult = ", var_mult,"var_div = ", var_div, "var_floor = ", var_floor,'var_exp = ',var_exp)
print("type(var1) = ", type(var1), "type(var2) = ", type(var2),"type(var_div) = ", type(var_div),"type(var_floor) = ", type(var_floor), "type(var_exp) = ", type(var_exp))

var1 =  4 var2 =  3 var_add =  7 var_mult =  12 var_div =  1.3333333333333333 var_floor =  1 var_exp =  64
type(var1) =  <class 'int'> type(var2) =  <class 'int'> type(var_div) =  <class 'float'> type(var_floor) =  <class 'int'> type(var_exp) =  <class 'int'>


##Conditional Operators and Loops

In [8]:
a = 45
b = 45
c = 20
if(a>b):  
  if a>c:
    print("a") # Note that there is no curly brackets to indicate a code section. Code section is indicated using indentation.
  else:
    print("c")
elif (b>c):
  print("b")
elif(a==b and a==c):
    print("=")
else:
  print("c")


b


In [9]:
#Loops
import numpy as np # import numpy library to be able to call numpy.arange() function

print("\nfor loop - loop over numbers: ")
for count in range(0,10,1): #range(start,stop,step)
  print(count,end=' ')

print("\nfor loop - loop over a list")
colors = ["red", "blue", "green", "black"]
for color in colors:
  print(color, "", end='')

print("\nfor loop - loop over floating point numbers")
for t in np.arange(0.0,1.0,0.10): # arange(start, stop, step) . for floating point iterates. similar function numpy.linspace
 print(t, end=' ')

print("\nwhile loop")
count = 10
while count>0:
  print(count, end=" ")
  count-=1


for loop - loop over numbers: 
0 1 2 3 4 5 6 7 8 9 
for loop - loop over a list
red blue green black 
for loop - loop over floating point numbers
0.0 0.1 0.2 0.30000000000000004 0.4 0.5 0.6000000000000001 0.7000000000000001 0.8 0.9 
while loop
10 9 8 7 6 5 4 3 2 1 

## Functions

In [10]:
def division(dividend,divisor):
  quotient = dividend/divisor
  return quotient

print(division(4,3)) #implicit argument mapping
print(division(dividend=4,divisor=3)) # explicit argument mapping 
print(division(divisor=4,dividend=3))

def my_arange(start,stop,step=1):
  my_list =[]
  current_val = start
  while (current_val < stop):
    my_list.append(current_val)
    current_val+=step
  return my_list

print("Function call with implicit argument mapping - my_arange(-10,10,1.5) = ", my_arange(-10,10,1.5))
print("Function call using default values - my_arange(-10,10) = ",my_arange(-10,10))
print("Function call with explicit argument mapping - my_arange(step=0.1,stop=1,start=0) = ", my_arange(step=0.1,stop=1,start=0))

1.3333333333333333
1.3333333333333333
0.75
Function call with implicit argument mapping - my_arange(-10,10,1.5) =  [-10, -8.5, -7.0, -5.5, -4.0, -2.5, -1.0, 0.5, 2.0, 3.5, 5.0, 6.5, 8.0, 9.5]
Function call using default values - my_arange(-10,10) =  [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Function call with explicit argument mapping - my_arange(step=0.1,stop=1,start=0) =  [0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7, 0.7999999999999999, 0.8999999999999999, 0.9999999999999999]


## Vectors and Matrix Operations

In [11]:
#Vectors and Matrices
import numpy as np

var_array = np.array([1,2,3,4])
print("Shape of var_array = ", var_array.shape)

var_row_vector = np.array([[1,2,3,4]])
print("Shape of var_row_vector = ", var_row_vector.shape)


print("var_array = ", var_array, ". var_vector = ", var_row_vector )

print("Transpose of var_array = ", var_array.T)
print("Transpose of var_row_vector = \n", var_row_vector.T)

print("Array multiplication with scalar = ", var_array * 3)
print("Vector multiplication with scalar = ", var_row_vector * 3)

var2_array = np.array([5,4,3,2])
var2_row_vector = np.array([[5,4,3,2]])

print("var_array * var2_array = ", var_array * var2_array.T) # '*' operator does a element wise multiplications
print("Example of Broadcasting (a terminology used in Python). var_row_vector * var2_row_vector = \n", var_row_vector.T * var2_row_vector) # example of broadcasting, where the arrays are expanded to match the dimensions 

print("matrix mult of var_row_vector and var2_row_vector = \n", np.matmul(var_row_vector.T,var2_row_vector))

M1 = np.random.randint(1,5,(8,2))
M2 = np.random.randint(1,5,(8,2))

print("matrix M1 = \n", M1, "\n matrix M2 = \n", M2)
print("M1.*M2 = \n", np.multiply(M1,M2))
print("M1*M2.T = \n", np.matmul(M1,M2.T))

Shape of var_array =  (4,)
Shape of var_row_vector =  (1, 4)
var_array =  [1 2 3 4] . var_vector =  [[1 2 3 4]]
Transpose of var_array =  [1 2 3 4]
Transpose of var_row_vector = 
 [[1]
 [2]
 [3]
 [4]]
Array multiplication with scalar =  [ 3  6  9 12]
Vector multiplication with scalar =  [[ 3  6  9 12]]
var_array * var2_array =  [5 8 9 8]
Example of Broadcasting (a terminology used in Python). var_row_vector * var2_row_vector = 
 [[ 5  4  3  2]
 [10  8  6  4]
 [15 12  9  6]
 [20 16 12  8]]
matrix mult of var_row_vector and var2_row_vector = 
 [[ 5  4  3  2]
 [10  8  6  4]
 [15 12  9  6]
 [20 16 12  8]]
matrix M1 = 
 [[2 1]
 [1 3]
 [2 4]
 [3 4]
 [2 4]
 [4 3]
 [1 1]
 [4 3]] 
 matrix M2 = 
 [[3 2]
 [4 1]
 [1 4]
 [1 2]
 [2 2]
 [1 3]
 [3 2]
 [3 2]]
M1.*M2 = 
 [[ 6  2]
 [ 4  3]
 [ 2 16]
 [ 3  8]
 [ 4  8]
 [ 4  9]
 [ 3  2]
 [12  6]]
M1*M2.T = 
 [[ 8  9  6  4  6  5  8  8]
 [ 9  7 13  7  8 10  9  9]
 [14 12 18 10 12 14 14 14]
 [17 16 19 11 14 15 17 17]
 [14 12 18 10 12 14 14 14]
 [18 19 16 10 14